---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - 'eval $(curl https://travis-perl.github.io/init) --auto'
language: perl
matrix:
  allow_failures:
    -
      env: COVERAGE=1
  fast_finish: 'true'
  include:
    -
      env: COVERAGE=1
      perl: '5.28'
notifications:
  email:
    if: repo = "tokuhirom/OrePAN2"
    on_failure: always
    on_success: always
    recipients:
      - olaf@wundersolutions.com
perl:
  - '5.8'
  - '5.10.0'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
  - '5.28'
